version: "3.3"


services:

  db:
    image: mysql:5.7
    volumes:
      - db_data1:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress1
      MYSQL_DATABASE: wordpress1
      MYSQL_USER: wordpress1
      MYSQL_PASSWORD: wordpress1

    
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_data1:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db1
      WORDPRESS_DB_USER: wordpress1
      WORDPRESS_DB_PASSWORD: wordpress1
      WORDPRESS_DB_NAME: wordpress1

volumes:
  db_data1: {}
  wordpress_data1: {}
